import os
from dotenv import load_dotenv

load_dotenv()

PATIENTS_COLLECTION = os.getenv("MONGODB_PATIENTS_COLLECTION")
APPOINTMENTS_COLLECTION = os.getenv("MONGODB_APPOINTMENTS_COLLECTION")
RECORDS_COLLECTION = os.getenv("MONGODB_RECORDS_COLLECTION")
